const data = [
  {
    name: "Mount Kilimanjaro Marangu",
    slug: "mount-kilimanjaro-marango",
    image: "https://cdn.tourradar.com/s3/tour/232x170/158591_7940ffdb.jpg",
    city: "Arusha",
    difficulty: "easy",
    length: 50,
    rating: 3,
  },
  {
    name: "Mount Kenya Trekking",
    slug: "mount-kenya-trekking",
    image: "https://cdn.tourradar.com/s3/tour/232x170/161115_b8821e37.jpg",
    city: "Nairobi",
    difficulty: "easy",
    length: 60,
    rating: 5,
  },
  {
    name: "Private Desert Tour",
    slug: "private-desert-tour",
    image: "https://cdn.tourradar.com/s3/tour/232x170/144393_5fea7294752dd.jpg",
    city: "Abu Dhabi",
    difficulty: "easy",
    length: 30,
    rating: 2,
  },
  {
    name: "Inca Trail Express",
    slug: "inca-trail-express",
    image: "https://cdn.tourradar.com/s3/review/232x170/48986_bf38499d.jpg",
    city: "Machu Picchu",
    difficulty: "hard",
    length: 70,
    rating: 4,
  },
  {
    name: "Everst Base Camp Short Trek",
    slug: "everst-base-camp-short-trek",
    image: "https://cdn.tourradar.com/s3/tour/232x170/75620_31534cee.jpg",
    city: "Kathmandu",
    difficulty: "hard",
    length: 140,
    rating: 5,
  },
  {
    name: "Italian Lakes",
    slug: "italian-lakes",
    image: "https://cdn.tourradar.com/s3/tour/232x170/62728_8acebc4a.jpg",
    city: "Milan",
    difficulty: "easy",
    length: 80,
    rating: 5,
  },
  {
    name: "Sapa Adventure",
    slug: "sapa-adventure",
    image: "https://cdn.tourradar.com/s3/tour/232x170/108804_cbfe262e.jpg",
    city: "Hanoi",
    difficulty: "medium",
    length: 50,
    rating: 3,
  },
  {
    name: "Northern Thailand Trip",
    slug: "northern-thailand-trip",
    image: "https://cdn.tourradar.com/s3/tour/232x170/60444_e53da9e1.jpg",
    city: "Chiang Mai",
    difficulty: "medium",
    length: 50,
    rating: 2,
  },
  {
    name: "Berber Village",
    slug: "berber-village",
    image: "https://cdn.tourradar.com/s3/review/232x170/103077_94f91b3b.jpg",
    city: "Marrakesh",
    difficulty: "medium",
    length: 40,
    rating: 1,
  },
  {
    name: "Hadrian's Wall Highlights",
    slug: "hardian's-wall-hgihlights",
    image: "https://cdn.tourradar.com/s3/tour/232x170/3893_69368249.jpg",
    city: "Carlise",
    difficulty: "medium",
    length: 70,
    rating: 3,
  },
  {
    name: "Week In Nepal",
    slug: "week-in-nepal",
    image: "https://cdn.tourradar.com/s3/tour/232x170/16565_5e53d7f0db75a.jpg",
    city: "kathmandu",
    difficulty: "hard",
    length: 80,
    rating: 2,
  },
];

export default data;
