const data = [
  {
    name: "Mount Kilimanjaro Marangu",
    slug: "mount-kilimanjaro-marango",
    image: "https://cdn.tourradar.com/s3/tour/232x170/158591_7940ffdb.jpg",
    city: "Arusha",
    difficulty: "easy",
    length: 50,
    rating: 3,
  },
  {
    name: "Mount Kenya Trekking",
    slug: "mount-kenya-trekking",
    image: "https://cdn.tourradar.com/s3/tour/232x170/161115_b8821e37.jpg",
    city: "Nairobi",
    difficulty: "easy",
    length: 60,
    rating: 5,
  },
  {
    name: "Private Desert Tour",
    slug: "private-desert-tour",
    image: "https://cdn.tourradar.com/s3/tour/232x170/144393_5fea7294752dd.jpg",
    city: "Abu Dhabi",
    difficulty: "easy",
    length: 30,
    rating: 2,
  },
  {
    name: "Inca Trail Express",
    slug: "inca-trail-express",
    image: "https://cdn.tourradar.com/s3/review/232x170/48986_bf38499d.jpg",
    city: "Machu Picchu",
    length: 70,
    rating: 4,
  },
  {
    name: "Walking in Paris",
    slug: "walking-in-paris",
    image:
      "https://images.unsplash.com/photo-1431274172761-fca41d930114?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    city: "Paris",
    difficulty: "easy",
    length: 10,
    rating: 3,
  },
  {
    name: "Everst Base Camp Short Trek",
    slug: "everst-base-camp-short-trek",
    image: "https://cdn.tourradar.com/s3/tour/232x170/75620_31534cee.jpg",
    city: "Kathmandu",
    difficulty: "hard",
    length: 140,
    rating: 5,
  },
  {
    name: "Italian Lakes",
    slug: "italian-lakes",
    image: "https://cdn.tourradar.com/s3/tour/232x170/62728_8acebc4a.jpg",
    city: "Milan",
    difficulty: "easy",
    length: 80,
    rating: 5,
  },
  {
    name: "Guided Bahrain Hike",
    slug: "guided-bahrain-hike",
    image: "https://img.ev.mu/images/attractions/4330/960x640/1319.jpg",
    city: "Manama",
    difficulty: "easy",
    length: 80,
    rating: 5,
  },
  {
    name: "Sapa Adventure",
    slug: "sapa-adventure",
    image: "https://cdn.tourradar.com/s3/tour/232x170/108804_cbfe262e.jpg",
    city: "Hanoi",
    difficulty: "medium",
    length: 50,
    rating: 3,
  },
  {
    name: "Northern Thailand Trip",
    slug: "northern-thailand-trip",
    image: "https://cdn.tourradar.com/s3/tour/232x170/60444_e53da9e1.jpg",
    city: "Chiang Mai",
    difficulty: "medium",
    length: 50,
    rating: 2,
  },
  {
    name: "Berber Village",
    slug: "berber-village",
    image: "https://cdn.tourradar.com/s3/review/232x170/103077_94f91b3b.jpg",
    city: "Marrakesh",
    difficulty: "medium",
    length: 40,
    rating: 1,
  },
  {
    name: "Hadrian's Wall Highlights",
    slug: "hardian's-wall-hgihlights",
    image: "https://cdn.tourradar.com/s3/tour/232x170/3893_69368249.jpg",
    city: "Carlise",
    difficulty: "medium",
    length: 70,
    rating: 3,
  },
  {
    name: "Week In Nepal",
    slug: "week-in-nepal",
    image: "https://cdn.tourradar.com/s3/tour/232x170/16565_5e53d7f0db75a.jpg",
    city: "kathmandu",
    difficulty: "hard",
    length: 80,
    rating: 2,
  },
  {
    name: "Summer in Dubai",
    slug: "summer-in-dubai",
    image:
      "https://images.unsplash.com/photo-1509710673830-ba94a3ba1b82?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1352&q=80",
    city: "Dubai",
    difficulty: "medium",
    length: 8,
    rating: 4,
  },
  {
    name: "Oman Mountain Private Hike ",
    slug: "oman-mountain-private-hike ",
    image:
      "https://wildlandtrekking.com/content/uploads/2020/03/image6-6-1.jpg",
    city: "Salalah",
    difficulty: "hard",
    length: 34,
    rating: 5,
  },
  {
    name: "Great Smoky Mountains ",
    slug: "great-smoky-mountains",
    image:
      "https://wildlandtrekking.com/content/uploads/2020/03/image3-3-2.jpg",
    city: "North Carolina",
    difficulty: "medium",
    length: 18,
    rating: 4,
  },
  {
    name: "Paddle & Hike Day Tour",
    slug: "paddle-hike-day-tour",
    image:
      "https://wildlandtrekking.com/content/uploads/2020/03/image1-2-4.jpg",
    city: "Salalah",
    difficulty: "hard",
    length: 50,
    rating: 3,
  },
  {
    name: "Trek Around Petra",
    slug: "trek-around-petra",
    image:
      "https://media.cntraveler.com/photos/5ad752c65523685aebcb55f7/16:9/w_2560%2Cc_limit/GettyImages-511984692.jpg",
    city: "Petra",
    difficulty: "easy",
    length: 17,
    rating: 5,
  },
  {
    name: "Best of Iceland Camping Tour",
    slug: "best-of-iceland-camping-tour",
    image:
      "https://wildlandtrekking.com/content/uploads/2020/03/Best-of-Iceland-Camping-Tour-image6-2-853x479.jpg",
    city: "Reykjavík",
    difficulty: "medium",
    length: 17,
    rating: 5,
  },
  {
    name: "Guided Kilimanjaro Trek",
    slug: "guided-kilimanjaro-trek",
    image:
      "https://wildlandtrekking.com/content/uploads/2020/03/image4-11-853x479.jpg",
    city: "Kilimanjaro",
    difficulty: "easy",
    length: 25,
    rating: 3,
  },
];

export default data;
